### ISSUE TITLE
Site bug: logo's reversed in multiple places

### ISSUE THREAD

**Issue by dead-claudia** [MithrilJS/mithril.js#2626]
I literally have no idea how this got missed, but the logo somehow got flipped at some point. Currently, we've got the following:

> Note: up = single ring on top + 2 rings on bottom, down = single ring on bottom + two rings on top. Checked = corrected, unchecked = pending fix.

- [x] Gitter: down
- [x] Open Collective: down
- [x] GitHub: down
- [x] [v0.2.1 logo](https://mithril.js.org/archive/v0.2.1/): down
- [ ] [v2.x logo](https://mithril.js.org/): down (up in repo, but rotated 180 degrees for some reason)
- [ ] [v2.x favicon](https://mithril.js.org/favicon.png): up

The correct orientation should be down (as was the case pre-v2), and the rest should be corrected.

**Comment by isiahmeadows** [comment]
The v2 site will be fixed at next release.
